# Funding channels for the project

# GitHub Sponsors username (personal or organization)
github: davidequirillo

# Buy Me a Coffee username (the slug from the URL buymeacoffee.com/YOUR_SLUG)
buy_me_a_coffee: davidequirillo

# Optional custom link (paypal)
custom: ['https://paypal.me/davidequirillo']
