# Funding channels for the project

# Ko-fi username (the slug from the URL ko-fi.com/YOUR_SLUG)
ko_fi: davidequirillo

# Buy Me a Coffee username (the slug from the URL buymeacoffee.com/YOUR_SLUG)
buy_me_a_coffee: davidequirillo

# GitHub Sponsors
custom: ["https://github.com/sponsors/davidequirillo"]
