"""add profile fields to users table

Revision ID: 0238ecb387eb
Revises: aa41b45acd6a
Create Date: 2026-02-06 20:43:24.343727

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0238ecb387eb'
down_revision: Union[str, Sequence[str], None] = 'aa41b45acd6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('street', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True))
    op.add_column('users', sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True))
    op.add_column('users', sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('users', sa.Column('province', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('users', sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True))
    op.add_column('users', sa.Column('birthdate', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True))
    op.add_column('users', sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone')
    op.drop_column('users', 'birthdate')
    op.drop_column('users', 'country')
    op.drop_column('users', 'province')
    op.drop_column('users', 'city')
    op.drop_column('users', 'postal_code')
    op.drop_column('users', 'street')
    # ### end Alembic commands ###
