"""added partial index on whitelist_entries for users not registered (fixed)

Revision ID: 068309dd8a45
Revises: 90cf5e36690f
Create Date: 2026-08-31 18:15:15.941652

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '068309dd8a45'
down_revision: Union[str, Sequence[str], None] = '90cf5e36690f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ixp_whitelist_entries_where_user_is_not_registered', 'whitelist_entries', ['created_by'], unique=False, postgresql_where='user_is_registered IS FALSE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ixp_whitelist_entries_where_user_is_not_registered', table_name='whitelist_entries', postgresql_where='user_is_registered IS FALSE')
    # ### end Alembic commands ###
