"""distance field in alerted_users table now is not null

Revision ID: 09d0ae40d962
Revises: 771f6d49e8b3
Create Date: 2026-07-15 16:04:57.713616

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '09d0ae40d962'
down_revision: Union[str, Sequence[str], None] = '771f6d49e8b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerted_users', 'distance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('alerts', 'address')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('address', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.alter_column('alerted_users', 'distance',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###
