"""added is_manager field in alerted users table

Revision ID: 0f5ff3e1ec9e
Revises: 2540d7e94a44
Create Date: 2026-05-21 00:23:03.175272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0f5ff3e1ec9e'
down_revision: Union[str, Sequence[str], None] = '2540d7e94a44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerted_users', sa.Column('is_manager', sa.Boolean(), nullable=False))
    op.alter_column('alerts', 'description',
               existing_type=sa.VARCHAR(length=256),
               type_=sqlmodel.sql.sqltypes.AutoString(length=512),
               existing_nullable=False)
    op.add_column('users', sa.Column('last_reliability_score_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_reliability_score_at')
    op.alter_column('alerts', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=512),
               type_=sa.VARCHAR(length=256),
               existing_nullable=False)
    op.drop_column('alerted_users', 'is_manager')
    # ### end Alembic commands ###
