"""refresh_tokens: add fcm_token field

Revision ID: 13b1c9ddffdd
Revises: 094e81ec4ad6
Create Date: 2026-03-02 00:42:28.402440

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '13b1c9ddffdd'
down_revision: Union[str, Sequence[str], None] = '094e81ec4ad6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('refresh_tokens', sa.Column('fcm_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('refresh_tokens', sa.Column('fcm_token_updated_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('refresh_tokens', 'fcm_token_updated_at')
    op.drop_column('refresh_tokens', 'fcm_token')
    # ### end Alembic commands ###
