"""for alerts, added partial index on is_closed field, when the value is false

Revision ID: 165ceeafdbc1
Revises: 384f153f74ce
Create Date: 2026-07-12 17:48:33.569929

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '165ceeafdbc1'
down_revision: Union[str, Sequence[str], None] = '384f153f74ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ixp_alerts_created_at_where_is_not_closed', 'alerts', ['created_at'], unique=False, postgresql_where='is_closed IS FALSE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ixp_alerts_created_at_where_is_not_closed', table_name='alerts', postgresql_where='is_closed IS FALSE')
    # ### end Alembic commands ###
