"""table users, reliability_score field not null

Revision ID: 188b35d94171
Revises: f81040c82363
Create Date: 2026-02-13 21:11:47.684809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '188b35d94171'
down_revision: Union[str, Sequence[str], None] = 'f81040c82363'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'reliability_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'reliability_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
