"""renamed is_registered field (in whitelist_entries table) to user_is_registered

Revision ID: 1abe633848a8
Revises: 79852fae2e8a
Create Date: 2026-07-28 17:49:50.289064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1abe633848a8'
down_revision: Union[str, Sequence[str], None] = '79852fae2e8a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whitelist_entries', sa.Column('user_is_registered', sa.Boolean(), nullable=True))
    op.drop_column('whitelist_entries', 'is_registered')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whitelist_entries', sa.Column('is_registered', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('whitelist_entries', 'user_is_registered')
    # ### end Alembic commands ###
