"""added column last_2fa_success_at in users table

Revision ID: 1beea92a2707
Revises: 2c891a0119ee
Create Date: 2026-04-16 00:21:11.100295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1beea92a2707'
down_revision: Union[str, Sequence[str], None] = '2c891a0119ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_2fa_success_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_2fa_success_at')
    # ### end Alembic commands ###
