"""some fixes on timestamps

Revision ID: 32877ccfa526
Revises: cdd8924cedd0
Create Date: 2026-01-10 01:25:25.003198

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '32877ccfa526'
down_revision: Union[str, Sequence[str], None] = 'cdd8924cedd0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whitelist', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whitelist', 'created_at')
    # ### end Alembic commands ###
