"""is_banned field in alerts and messages now is not nullable

Revision ID: 384f153f74ce
Revises: 3e9ac569c8a0
Create Date: 2026-07-06 15:46:26.260023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '384f153f74ce'
down_revision: Union[str, Sequence[str], None] = '3e9ac569c8a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'is_banned',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('messages', 'is_banned',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('messages', 'is_banned',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('alerts', 'is_banned',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
