"""rename lat and lon with gps_lat and gps_lon

Revision ID: 39aa106c86ba
Revises: 063031579d9f
Create Date: 2026-01-06 00:54:54.123749

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '39aa106c86ba'
down_revision: Union[str, Sequence[str], None] = '063031579d9f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('gps_lat', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('gps_lon', sa.Float(), nullable=True))
    op.drop_column('users', 'lon')
    op.drop_column('users', 'lat')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('lat', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('lon', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('users', 'gps_lon')
    op.drop_column('users', 'gps_lat')
    # ### end Alembic commands ###
