"""added is_banned flag to alerts and messages

Revision ID: 3e9ac569c8a0
Revises: 56174dbb44cd
Create Date: 2026-07-06 15:43:35.758712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3e9ac569c8a0'
down_revision: Union[str, Sequence[str], None] = '56174dbb44cd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('is_banned', sa.Boolean(), nullable=True))
    op.add_column('messages', sa.Column('is_banned', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('messages', 'is_banned')
    op.drop_column('alerts', 'is_banned')
    # ### end Alembic commands ###
