"""Little fix on is_manager field (alerted users table)

Revision ID: 40cb40609c30
Revises: 0f5ff3e1ec9e
Create Date: 2026-05-21 23:34:41.780597

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '40cb40609c30'
down_revision: Union[str, Sequence[str], None] = '0f5ff3e1ec9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
