"""Removed index user_is_registered on whitelist_entries table

Revision ID: 4b629f7d4677
Revises: 068309dd8a45
Create Date: 2026-08-31 22:03:29.466560

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '4b629f7d4677'
down_revision: Union[str, Sequence[str], None] = '068309dd8a45'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ixp_whitelist_entries_where_user_is_not_registered'), table_name='whitelist_entries', postgresql_where='(user_is_registered IS FALSE)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ixp_whitelist_entries_where_user_is_not_registered'), 'whitelist_entries', ['created_by'], unique=False, postgresql_where='(user_is_registered IS FALSE)')
    # ### end Alembic commands ###
