"""in whitelist_entries table, user_is_registered now cannot be null

Revision ID: 55395cdcd69b
Revises: 1abe633848a8
Create Date: 2026-07-28 17:54:08.221516

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '55395cdcd69b'
down_revision: Union[str, Sequence[str], None] = '1abe633848a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('whitelist_entries', 'user_is_registered',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('whitelist_entries', 'user_is_registered',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
