"""alerts table, messages_num not null constraint

Revision ID: 58cb75ce16a4
Revises: ec71308ba88f
Create Date: 2026-08-14 19:17:39.588060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '58cb75ce16a4'
down_revision: Union[str, Sequence[str], None] = 'ec71308ba88f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'messages_num',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'messages_num',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
