"""rename login_attemps field to login_2fa_attemps

Revision ID: 6706499f9375
Revises: 92797c166eae
Create Date: 2026-01-24 01:52:33.461213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6706499f9375'
down_revision: Union[str, Sequence[str], None] = '92797c166eae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login_2fa_attempts', sa.Integer(), nullable=True))
    op.drop_column('users', 'login_attempts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login_attempts', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('users', 'login_2fa_attempts')
    # ### end Alembic commands ###
