"""added 'distance' field to alerted_users table

Revision ID: 771f6d49e8b3
Revises: 165ceeafdbc1
Create Date: 2026-07-15 15:49:38.409696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '771f6d49e8b3'
down_revision: Union[str, Sequence[str], None] = '165ceeafdbc1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerted_users', sa.Column('distance', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerted_users', 'distance')
    # ### end Alembic commands ###
