"""in whitelist_entries table, is_registered now cannot be null

Revision ID: 79852fae2e8a
Revises: c835ddeb0139
Create Date: 2026-07-28 16:22:55.210286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '79852fae2e8a'
down_revision: Union[str, Sequence[str], None] = 'c835ddeb0139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('whitelist_entries', 'is_registered',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('whitelist_entries', 'is_registered',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
