"""address field re-added in alerts table

Revision ID: 8fdcb5e64646
Revises: 09d0ae40d962
Create Date: 2026-07-15 16:17:27.664252

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '8fdcb5e64646'
down_revision: Union[str, Sequence[str], None] = '09d0ae40d962'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'address')
    # ### end Alembic commands ###
