"""added partial index on whitelist_entries for users not registered

Revision ID: 90cf5e36690f
Revises: 6d959d3e97da
Create Date: 2026-08-31 18:11:38.466010

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '90cf5e36690f'
down_revision: Union[str, Sequence[str], None] = '6d959d3e97da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
