"""alter login attempts nullable false

Revision ID: 92797c166eae
Revises: 9857c86548ee
Create Date: 2026-01-23 01:38:51.112948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '92797c166eae'
down_revision: Union[str, Sequence[str], None] = '9857c86548ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'login_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'login_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
