"""drop created_at index in alerts table

Revision ID: 95150131e2ac
Revises: dd0a779aa96b
Create Date: 2026-02-26 23:55:32.933913

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '95150131e2ac'
down_revision: Union[str, Sequence[str], None] = 'dd0a779aa96b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    # ### end Alembic commands ###
