"""In alerts table, expanded field is not null

Revision ID: 95ca43816430
Revises: c62b590ee092
Create Date: 2026-07-24 16:39:10.519763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '95ca43816430'
down_revision: Union[str, Sequence[str], None] = 'c62b590ee092'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'is_expanded',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alerts', 'is_expanded',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
