"""add login otp fields

Revision ID: 9857c86548ee
Revises: f9de0772917a
Create Date: 2026-01-23 01:34:53.023832

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9857c86548ee'
down_revision: Union[str, Sequence[str], None] = 'f9de0772917a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('login_expires_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('login_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('login_locked_until', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('last_login_mail_code_at', sa.DateTime(), nullable=True))
    op.add_column('users', sa.Column('login_code_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'login_code_hash')
    op.drop_column('users', 'last_login_mail_code_at')
    op.drop_column('users', 'login_locked_until')
    op.drop_column('users', 'login_attempts')
    op.drop_column('users', 'login_expires_at')
    # ### end Alembic commands ###
