"""add spread_count and is_pending fields to alerts table

Revision ID: 9ff8400cfbe4
Revises: aff243e02827
Create Date: 2026-06-22 15:17:34.369089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '9ff8400cfbe4'
down_revision: Union[str, Sequence[str], None] = 'aff243e02827'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('is_pending', sa.Boolean(), nullable=False))
    op.add_column('alerts', sa.Column('spread_count', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'spread_count')
    op.drop_column('alerts', 'is_pending')
    # ### end Alembic commands ###
