"""add authorized_at field to users table

Revision ID: a0671a670bd3
Revises: d6838baf29e7
Create Date: 2026-02-04 16:23:11.883889

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a0671a670bd3'
down_revision: Union[str, Sequence[str], None] = 'd6838baf29e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('authorized_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'authorized_at')
    # ### end Alembic commands ###
