"""users: delete status field, and add is_reliable, is_blocked

Revision ID: a0af6c0ed5a2
Revises: 188b35d94171
Create Date: 2026-02-17 23:22:43.551212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a0af6c0ed5a2'
down_revision: Union[str, Sequence[str], None] = '188b35d94171'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_reliable', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True))
    op.drop_column('users', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('users', 'notes')
    op.drop_column('users', 'is_blocked')
    op.drop_column('users', 'is_reliable')
    # ### end Alembic commands ###
