"""users: is_reliable, is_blocked cannot be null

Revision ID: a7513e4be8a5
Revises: a0af6c0ed5a2
Create Date: 2026-02-17 23:26:31.003168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'a7513e4be8a5'
down_revision: Union[str, Sequence[str], None] = 'a0af6c0ed5a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_reliable',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('users', 'is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_blocked',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('users', 'is_reliable',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
