"""added is_expanded field to alerts table

Revision ID: c62b590ee092
Revises: ec0af1c90252
Create Date: 2026-07-24 16:37:59.872688

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c62b590ee092'
down_revision: Union[str, Sequence[str], None] = 'ec0af1c90252'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('is_expanded', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'is_expanded')
    # ### end Alembic commands ###
