"""add composite index on alerts table (created at and gps coords)

Revision ID: c81646dd8879
Revises: 95150131e2ac
Create Date: 2026-02-27 00:03:01.206838

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c81646dd8879'
down_revision: Union[str, Sequence[str], None] = '95150131e2ac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_alerts_created_at_lat_long', 'alerts', ['created_at', 'latitude', 'longitude'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_alerts_created_at_lat_long', table_name='alerts')
    # ### end Alembic commands ###
