"""added registration_type, registration_role, is_registered to whitelist_entries table

Revision ID: c835ddeb0139
Revises: 9df55efa7080
Create Date: 2026-07-28 16:01:36.861707

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c835ddeb0139'
down_revision: Union[str, Sequence[str], None] = '9df55efa7080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('whitelist_entries', sa.Column('registration_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True))
    op.add_column('whitelist_entries', sa.Column('registration_role', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True))
    op.add_column('whitelist_entries', sa.Column('is_registered', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('whitelist_entries', 'is_registered')
    op.drop_column('whitelist_entries', 'registration_role')
    op.drop_column('whitelist_entries', 'registration_type')
    # ### end Alembic commands ###
