"""add is_chief field to users

Revision ID: ceb21ac2c7c0
Revises: 07712f18f532
Create Date: 2026-01-23 01:17:55.854754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ceb21ac2c7c0'
down_revision: Union[str, Sequence[str], None] = '07712f18f532'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_chief', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'is_chief')
    # ### end Alembic commands ###
