"""remove email hash column from users table

Revision ID: d0658b1b0dcd
Revises: 6b7556cd0807
Create Date: 2026-02-20 00:30:39.513179

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd0658b1b0dcd'
down_revision: Union[str, Sequence[str], None] = '6b7556cd0807'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('users_email_hash_key'), 'users', type_='unique')
    op.drop_column('users', 'email_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_unique_constraint(op.f('users_email_hash_key'), 'users', ['email_hash'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
