"""add aauthorized_by field in users table

Revision ID: d6838baf29e7
Revises: a00e2ac6fb7b
Create Date: 2026-02-02 00:37:25.563543

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'd6838baf29e7'
down_revision: Union[str, Sequence[str], None] = 'a00e2ac6fb7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('authorized_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'authorized_by')
    # ### end Alembic commands ###
