"""alerts, add some fields: latitude, longitude, address

Revision ID: dd0a779aa96b
Revises: d0658b1b0dcd
Create Date: 2026-02-26 20:01:11.979310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dd0a779aa96b'
down_revision: Union[str, Sequence[str], None] = 'd0658b1b0dcd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('latitude', sa.Float(), nullable=False))
    op.add_column('alerts', sa.Column('longitude', sa.Float(), nullable=False))
    op.add_column('alerts', sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True))
    op.drop_index(op.f('ix_whitelist_entries_email'), table_name='whitelist_entries')
    op.create_index(op.f('ix_whitelist_entries_email'), 'whitelist_entries', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_whitelist_entries_email'), table_name='whitelist_entries')
    op.create_index(op.f('ix_whitelist_entries_email'), 'whitelist_entries', ['email'], unique=False)
    op.drop_column('alerts', 'address')
    op.drop_column('alerts', 'longitude')
    op.drop_column('alerts', 'latitude')
    # ### end Alembic commands ###
