"""login_attemps field not nullable

Revision ID: e0c60493a76b
Revises: 6706499f9375
Create Date: 2026-01-24 01:56:21.196816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e0c60493a76b'
down_revision: Union[str, Sequence[str], None] = '6706499f9375'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'login_2fa_attempts',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'login_2fa_attempts',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
