"""create tables: whitelist_entries, users, alerts, etc. etc.

Revision ID: e2870de89414
Revises: 
Create Date: 2026-08-06 16:44:41.558578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'e2870de89414'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('firstname', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('surname', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('language', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('is_superuser', sa.Boolean(), nullable=False),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_officer', sa.Boolean(), nullable=False),
    sa.Column('is_chief', sa.Boolean(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('is_reliable', sa.Boolean(), nullable=False),
    sa.Column('reliability_score', sa.Integer(), nullable=False),
    sa.Column('last_reliability_score_at', sa.DateTime(), nullable=True),
    sa.Column('hero_score', sa.Integer(), nullable=False),
    sa.Column('is_blocked', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('activation_expires_at', sa.DateTime(), nullable=True),
    sa.Column('pending_delete_since', sa.DateTime(), nullable=True),
    sa.Column('reset_expires_at', sa.DateTime(), nullable=True),
    sa.Column('reset_attempts', sa.Integer(), nullable=False),
    sa.Column('reset_locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_reset_mail_code_at', sa.DateTime(), nullable=True),
    sa.Column('last_reset_done_at', sa.DateTime(), nullable=False),
    sa.Column('last_reset_mail_confirmation_at', sa.DateTime(), nullable=True),
    sa.Column('login_expires_at', sa.DateTime(), nullable=True),
    sa.Column('login_2fa_attempts', sa.Integer(), nullable=False),
    sa.Column('login_locked_until', sa.DateTime(), nullable=True),
    sa.Column('last_login_mail_code_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_done_at', sa.DateTime(), nullable=True),
    sa.Column('last_2fa_success_at', sa.DateTime(), nullable=True),
    sa.Column('last_login_mail_confirmation_at', sa.DateTime(), nullable=True),
    sa.Column('last_refresh_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('authorized_by', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('authorized_at', sa.DateTime(), nullable=True),
    sa.Column('street', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('postal_code', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=True),
    sa.Column('city', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('province', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('birthdate', sqlmodel.sql.sqltypes.AutoString(length=10), nullable=True),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('password_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('activation_code', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('reset_code_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('login_code_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index('ixc_users_authorized_by_id', 'users', ['authorized_by', 'id'], unique=False)
    op.create_index('ixc_users_surname_id', 'users', ['surname', 'id'], unique=False)
    op.create_index('ixcp_users_role_id_where_role_not_null', 'users', ['role', 'id'], unique=False, postgresql_where='role IS NOT NULL')
    op.create_index('ixp_users_id_where_is_admin', 'users', ['id'], unique=False, postgresql_where='is_admin IS TRUE')
    op.create_index('ixp_users_id_where_is_blocked', 'users', ['id'], unique=False, postgresql_where='is_blocked IS TRUE')
    op.create_index('ixp_users_id_where_is_chief', 'users', ['id'], unique=False, postgresql_where='is_chief IS TRUE')
    op.create_index('ixp_users_id_where_is_not_reliable', 'users', ['id'], unique=False, postgresql_where='is_reliable IS FALSE')
    op.create_index('ixp_users_id_where_is_officer', 'users', ['id'], unique=False, postgresql_where='is_officer IS TRUE')
    op.create_index('ixp_users_pending_delete_since_where_not_null', 'users', ['pending_delete_since'], unique=False, postgresql_where='pending_delete_since IS NOT NULL')
    op.create_table('whitelist_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('created_by', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('registration_type', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('registration_role', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('user_is_registered', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_whitelist_entries_email'), 'whitelist_entries', ['email'], unique=True)
    op.create_index('ixc_whitelist_entries_created_by_id', 'whitelist_entries', ['created_by', 'id'], unique=False)
    op.create_table('alerts',
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('radius', sa.Float(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('severity', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('is_pending', sa.Boolean(), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('is_expanded', sa.Boolean(), nullable=False),
    sa.Column('spread_count', sa.Integer(), nullable=False),
    sa.Column('is_closed', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_user_id'), 'alerts', ['user_id'], unique=False)
    op.create_index('ixc_alerts_created_at_lat_long', 'alerts', ['created_at', 'latitude', 'longitude'], unique=False)
    op.create_index('ixp_alerts_created_at_where_is_not_closed', 'alerts', ['created_at'], unique=False, postgresql_where='is_closed IS FALSE')
    op.create_index('ixp_alerts_created_at_where_type_general', 'alerts', ['created_at'], unique=False, postgresql_where="type = 'general'")
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('raw_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('ip_address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('device_info', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fcm_token', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('fcm_token_updated_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_user_id'), 'refresh_tokens', ['user_id'], unique=False)
    op.create_table('alerted_users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('distance', sa.Float(), nullable=False),
    sa.Column('is_manager', sa.Boolean(), nullable=False),
    sa.Column('vote', sa.Integer(), nullable=False),
    sa.Column('closing_vote', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerted_users_alert_id'), 'alerted_users', ['alert_id'], unique=False)
    op.create_index(op.f('ix_alerted_users_user_id'), 'alerted_users', ['user_id'], unique=False)
    op.create_table('messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(length=512), nullable=False),
    sa.Column('is_banned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_messages_alert_id'), 'messages', ['alert_id'], unique=False)
    op.create_index(op.f('ix_messages_user_id'), 'messages', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_user_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_alert_id'), table_name='messages')
    op.drop_table('messages')
    op.drop_index(op.f('ix_alerted_users_user_id'), table_name='alerted_users')
    op.drop_index(op.f('ix_alerted_users_alert_id'), table_name='alerted_users')
    op.drop_table('alerted_users')
    op.drop_index(op.f('ix_refresh_tokens_user_id'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('ixp_alerts_created_at_where_type_general', table_name='alerts', postgresql_where="type = 'general'")
    op.drop_index('ixp_alerts_created_at_where_is_not_closed', table_name='alerts', postgresql_where='is_closed IS FALSE')
    op.drop_index('ixc_alerts_created_at_lat_long', table_name='alerts')
    op.drop_index(op.f('ix_alerts_user_id'), table_name='alerts')
    op.drop_table('alerts')
    op.drop_index('ixc_whitelist_entries_created_by_id', table_name='whitelist_entries')
    op.drop_index(op.f('ix_whitelist_entries_email'), table_name='whitelist_entries')
    op.drop_table('whitelist_entries')
    op.drop_index('ixp_users_pending_delete_since_where_not_null', table_name='users', postgresql_where='pending_delete_since IS NOT NULL')
    op.drop_index('ixp_users_id_where_is_officer', table_name='users', postgresql_where='is_officer IS TRUE')
    op.drop_index('ixp_users_id_where_is_not_reliable', table_name='users', postgresql_where='is_reliable IS FALSE')
    op.drop_index('ixp_users_id_where_is_chief', table_name='users', postgresql_where='is_chief IS TRUE')
    op.drop_index('ixp_users_id_where_is_blocked', table_name='users', postgresql_where='is_blocked IS TRUE')
    op.drop_index('ixp_users_id_where_is_admin', table_name='users', postgresql_where='is_admin IS TRUE')
    op.drop_index('ixcp_users_role_id_where_role_not_null', table_name='users', postgresql_where='role IS NOT NULL')
    op.drop_index('ixc_users_surname_id', table_name='users')
    op.drop_index('ixc_users_authorized_by_id', table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
