"""add is_chief field to users

Revision ID: eb06d75f1925
Revises: ceb21ac2c7c0
Create Date: 2026-01-23 01:25:22.946367

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eb06d75f1925'
down_revision: Union[str, Sequence[str], None] = 'ceb21ac2c7c0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_official',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_official',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
