"""added hero_score field to users table

Revision ID: eb6633be1413
Revises: 8fdcb5e64646
Create Date: 2026-07-23 14:56:18.687194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'eb6633be1413'
down_revision: Union[str, Sequence[str], None] = '8fdcb5e64646'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('hero_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'hero_score')
    # ### end Alembic commands ###
