"""hero_score field is not null

Revision ID: ec0af1c90252
Revises: eb6633be1413
Create Date: 2026-07-23 14:57:34.094378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ec0af1c90252'
down_revision: Union[str, Sequence[str], None] = 'eb6633be1413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hero_score',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'hero_score',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
