"""added message_num to alerts table

Revision ID: ec71308ba88f
Revises: e2870de89414
Create Date: 2026-08-14 19:15:33.623985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'ec71308ba88f'
down_revision: Union[str, Sequence[str], None] = 'e2870de89414'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('messages_num', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('alerts', 'messages_num')
    # ### end Alembic commands ###
