"""add reliability_score field to users

Revision ID: f81040c82363
Revises: e0ad457b5017
Create Date: 2026-02-13 21:09:24.175815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f81040c82363'
down_revision: Union[str, Sequence[str], None] = 'e0ad457b5017'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('reliability_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'reliability_score')
    # ### end Alembic commands ###
