"""alter table is_chief nullable false

Revision ID: f9de0772917a
Revises: eb06d75f1925
Create Date: 2026-01-23 01:27:41.360428

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'f9de0772917a'
down_revision: Union[str, Sequence[str], None] = 'eb06d75f1925'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_chief',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_chief',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
